sudo: required
dist: trusty
language: cpp

matrix:
  include:

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - unrar
      env:
        - COMPILER=g++-5

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - unrar
      env:
        - COMPILER=g++-4.9

    - compiler: gcc
      addons:
        apt:
          packages:
            - unrar
      env:
        - COMPILER=g++-4.8
        - CXXFLAGS="-std=c++11 -O2 -s"
        - CONFIGUREOPTS="--disable-cpp-check"

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - unrar
      env:
        - COMPILER=clang++-3.6

script:
  - $COMPILER --version
  - CXX=$COMPILER ./configure $CONFIGUREOPTS --enable-tests && make
  - ./nzbget --tests
